version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 12
    commands:
      - ls
      - pip install -r requirements.txt
  build:
    commands:
      - cdk synth
artifacts:
  files: '**/*'