version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
      nodejs: latest
    commands:
      # - ls -al
      - npm install -g aws-cdk
      - cdk --version
      - pip install -r requirements.txt
  build:
    commands:
      - cdk deploy
artifacts:
  files: '**/*'