version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 16
    commands:
      # - ls -al
      - npm install -g aws-cdk
      - pip install -r requirements.txt
  build:
    commands:
      - cdk deploy
artifacts:
  files: '**/*'